name: flutterbook
description: A storyboard tool to accelerate the development of Flutter widgets.
version: 0.1.5
homepage: https://github.com/GhostWalker562/flutterbook

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.3
  device_preview: ^0.7.5
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  google_fonts: ^2.1.0
  provider: ^5.0.0
  recase: ^4.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
